[profile.default]
src = "contracts/src"
test = "contracts/test"
out = "contracts/out"
script = "contracts/script"
cache_path = "contracts/cache"
broadcast = "contracts/broadcast"
libs = ["node_modules", "dependencies"]
solc_version = "0.8.20"

remappings = [
    "@uniswap/v3-core/=dependencies/tnt-core-0.1.0/lib/uniswap-v3-core/contracts/",
    "@layerzerolabs/lz-evm-messagelib-v2/=node_modules/@layerzerolabs/lz-evm-messagelib-v2/",
    "@layerzerolabs/lz-evm-protocol-v2/=node_modules/@layerzerolabs/lz-evm-protocol-v2/",
    "@layerzerolabs/lz-evm-v1-0.7/=node_modules/@layerzerolabs/lz-evm-v1-0.7/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "core/=dependencies/tnt-core-0.1.0/src/",
    "forge-std/=dependencies/forge-std-1.9.5/src/",
    "tnt-core/=dependencies/tnt-core-0.1.0/src/",
    "solidity-bytes-utils=node_modules/solidity-bytes-utils/",
]

[dependencies]
forge-std = "1.9.5"
tnt-core = "0.1.0"
